name: GraphQL

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  checks: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  schema-up-to-date:
    name: Schema is up to date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - run: cargo run --bin export-schema -- schema.graphql.generated

      - run: diff -u schema.graphql schema.graphql.generated

  breaking-changes:
    name: Detect breaking changes
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: graphql-hive/graphql-inspector@master
        with:
          schema: 'main:schema.graphql'
          fail-on-breaking: false
