name: Test

on:
  workflow_call:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-rustdoc:
    name: Test (Rustdoc)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Test
        run: make test-doc

  test-rust:
    name: Test (Rust)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov

      - name: Test
        run: make test-coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          fail_ci_if_error: false
          files: lcov.info
          flags: rust
          token: ${{ secrets.CODECOV_TOKEN }}
